spring.application.name=bookstore
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=33uC3KEpFmp7RKM.root
spring.datasource.password=wxfXU3XHy8GAnIHi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8090
server.forward-headers-strategy=framework

spring.data.redis.host=redis-12150.crce182.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=12150
spring.data.redis.username=default
spring.data.redis.password=Mic92yELTdUCKMRmfpONxZK3I63THQDc
spring.data.redis.ssl.enabled=false
